import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import { motion } from 'framer-motion';
import PostsContainer from '@/components/public/PostsContainer';
import { postsFetch, postsUrl } from '@/services/postsFetch';

export default function Home() {

  const [posts, setPosts] = useState(null)

  const getPosts = async () => {
    const res= await fetch(postsUrl).then(res=>res.json())
    setPosts(res)
  }

  useEffect(()=>{
    getPosts()
  }, [])

   return (
    <>
      <Head>
        <title>PubliShare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        key="home"
        style={{ width: '100%' }}
      >
      </motion.div>
      <PostsContainer posts={posts}/>
    </>
  )
}
