import React, {useState, useEffect} from 'react';
import Head from 'next/head';
import { motion } from 'framer-motion';
import PostsContainer from '@/components/public/PostsContainer';
import { postsFetch, postsUrl } from '@/services/postsFetch';
import styled from 'styled-components';


const TitleContainer = styled.div`
width: 90%;
margin-top: 20px;
margin-bottom: -20px;
@media (min-width: 768px) {
  width: 70%;
}
`

const Title = styled.h3`
font-style: normal;
font-weight: 600;
font-size: 16px;
line-height: 28px;
justify-self: start;
align-self: start;

@media (min-width: 768px) {
      font-size: 20px;
  }
`

export default function Home() {

  const [posts, setPosts] = useState(null)


  const getPosts = async () => {
    const res= await fetch(postsUrl).then(res=>res.json())
    setPosts(res)
  }

  useEffect(()=>{
    getPosts()
  }, [])

   return (
    <>
      <Head>
        <title>PubliShare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        key="home"
        style={{ width: '100%' }}
      >
      </motion.div>
      <TitleContainer>
        <Title>
          Publicaciones populares
        </Title>
      </TitleContainer>
      <PostsContainer posts={posts}/>
    </>
  )
}
